### ISSUE TITLE
input_maker_create fails on empty table

### ISSUE THREAD

**Issue by lcjury** [GrafiteInc/FormMaker#20]
I have the following inside a blade file:

`
@input_maker('category', [
   'type' => 'relationship',
   'model' => 'App\Models\Category',
   'label' => 'name',
   'value' => 'id'
 `

That throws an error saying that options are required. To reproduce the error, the categories table must be empty, when I add at least one row to the table the error stop appearing.

**Comment by mlantz** [comment]
This has been fixed in a more recent release
