### ISSUE TITLE
There should be an attribute to define input ID

### ISSUE THREAD

**Issue by zimarai** [GrafiteInc/FormMaker#26]
There should be an attribute to define individual input IDs, at least for checkbox and radio inputs. I found this problem trying to define two radio buttons with the same name, so the user could choose one or another option. The problem is that they consecuently inherit the name as ID, and that's not right.

```
public function makeRadio($config, $selected, $custom)
{
     return '<input ' . $custom . ' id="' . ucfirst($config['name']) . '" ' . $selected . ' type="radio" name="' . $config['name'] . '">';
}
```
`yab/formmaker/src/Generators/HtmlGenerator.php`

**Comment by mlantz** [comment]
Very true, I'll make a note to review that in the next couple days thanks.

**Comment by mlantz** [comment]
Sorry for the MASSIVE delay this will be in the next release this week
