### ISSUE TITLE
@input_maker_label: cannot create label with different name to linked input id

### ISSUE THREAD

**Issue by NickWhiu** [GrafiteInc/FormMaker#31]
**Steps to reproduce**
Try create a label such as `<label for="job_number">Job Number</label>` with `input_maker_label`

**Expected**
A way to create a label with a different name to the input ID that is linked with for attribute

For example
`input_maker_label('input_id', ['label' => 'Label Name'])`
or `input_maker_label('Label Name', ['for' => 'input_id'])`
outputting
`<label for="input_id">label name</label>`

**Actual**
With InputMaker->label you are forced to make the name the same as the for=".." attribute, which cannot be overridden.
`<label for="input_id">input_id</label>`

Or am I missing something? I see no alternative in the source code or documentation.
Thanks.

**Comment by mlantz** [comment]
Is there a reason to make it different than the corresponding input id? https://www.w3schools.com/tags/att_label_for.asp

**Comment by NickWhiu** [comment]
Yes, thats why the two parameters are declared in different places in HTML. Sometimes you dont have control over the field name that the backing API expects, often lowercase and with underscores, when the label name you want to show the user often has capitals and spaces.

e.g. this is often what people need: `<label for="first_name">First Name</label>`

**Comment by mlantz** [comment]
I currently have the for matching the corresponding ID but I see what you mean with the label maker now, I'll work on a fix for that :)

**Comment by mlantz** [comment]
This is now in available in the latest version
