### ISSUE TITLE
Multi select pre-fill existing values on edit screen error: Call to undefined method Illuminate\Database\Query\Builder::roles()

### ISSUE THREAD

**Issue by shabaz-ejaz** [GrafiteInc/FormMaker#32]
I am using the standard User - Roles relationship tables as set up by default in Quarx.

When I try to use formMaker to show existing roles on the user edit screen I get the following error:

> [2018-04-16 16:14:24] local.ERROR: Call to undefined method Illuminate\Database\Query\Builder::roles() (View: C:\wamp\www\proj\resources\views\admin\users\edit.blade.php)

Here is my edit blade file:

```
 {!! FormMaker::fromObject($user,
           [
           'name',
           'meta[first_name]' => [
                'alt_name' => 'First Name',
            ],
           'meta[roles]' => [
                'alt_name' => 'Roles',
                'custom' => 'multiple',
                'multiple' => true,
                'class' => auth()->user(),
                'method' => 'roles',
                'type' => 'relationship',
                'model' => 'App\Models\Role',
                'label' => 'label', // the field for the label in the select input generated
                'value' => 'name' // the field for the label in the select input generated
            ],
          ] ) !!}

        {!! Form::submit('Update', ['class' => 'btn btn-primary pull-right']) !!}

 {!! Form::close() !!}
```

If I remove the `method` and `class` attributes then it shows the multi select but all of the options are selected by default:

```
'meta[roles]' => [
                'alt_name' => 'Roles',
                'custom' => 'multiple',
                'multiple' => true,
                'type' => 'relationship',
                'model' => 'App\Models\Role',
                'label' => 'label', // the field for the label in the select input generated
                'value' => 'name' // the field for the label in the select input generated
            ]
```

![2018-04-16_16h27_42](https://user-images.githubusercontent.com/29374282/38819393-221432ec-4193-11e8-8c3f-1fe3a3316d79.png)

Not sure what's going on here, I am using `"yab/laracogs": "^2.3",`

**Comment by shabaz-ejaz** [comment]
Any updates on this?

**Comment by shabaz-ejaz** [comment]
Still no updates on this?

**Comment by shabaz-ejaz** [comment]
Still nothing..... I'm gonna do this every day until I get a response.

**Comment by shabaz-ejaz** [comment]
Still waiting..... No response.

**Comment by shabaz-ejaz** [comment]
Still waiting 8th day and still going....

**Comment by shabaz-ejaz** [comment]
@mlantz Where u at bro?

**Comment by mlantz** [comment]
Always courteous, the documentation states that we don't do support on 2.3. You can switch over to Grafite Builder, or switch directly to the FormMaker package with the latest version. This was fixed in a more recent version of FormMaker.

**Comment by shabaz-ejaz** [comment]
Well that was an anti-climax 😆
